#!/usr/bin/env python3
"""Diagnostic script: inspect candidate generation, diversity filtering, and post-routing rescoring.

Answers three questions:
1. Are candidates from different regions being generated by _find_top_k_layouts()?
2. Does _diversify_candidates() actually change anything?
3. Does _post_routing_rescore() see different 2Q gate counts, or are they all identical?

Usage::

    python scripts/diagnose_candidates.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from qiskit.circuit import Measure, Parameter
from qiskit.circuit.library import CZGate, HGate, RZGate, SXGate, XGate
from qiskit.transpiler import InstructionProperties, Target
from rich.console import Console
from rich.table import Table

from qb_compiler.calibration.models.backend_properties import BackendProperties
from qb_compiler.ir.circuit import QBCircuit
from qb_compiler.ir.operations import QBGate
from qb_compiler.passes.mapping.calibration_mapper import CalibrationMapper, CalibrationMapperConfig

console = Console()

GHZ_SIZES = [3, 5, 8, 10]


# ── Build Qiskit Target from real calibration ──────────────────────────────


def build_target(props: BackendProperties) -> Target:
    """Build a Qiskit Target from BackendProperties with real error rates."""
    n_qubits = props.n_qubits
    target = Target(num_qubits=n_qubits)

    cz_props: dict[tuple[int, int], InstructionProperties | None] = {}
    for gp in props.gate_properties:
        if len(gp.qubits) == 2:
            cz_props[gp.qubits] = InstructionProperties(
                error=gp.error_rate,
                duration=gp.gate_time_ns * 1e-9 if gp.gate_time_ns else 68e-9,
            )
    target.add_instruction(CZGate(), cz_props)

    sq_props: dict[tuple[int, ...], InstructionProperties | None] = {
        (q,): None for q in range(n_qubits)
    }
    theta = Parameter("theta")
    target.add_instruction(RZGate(theta), sq_props)
    target.add_instruction(SXGate(), sq_props)
    target.add_instruction(XGate(), sq_props)
    target.add_instruction(HGate(), sq_props)
    target.add_instruction(Measure(), sq_props)

    return target


# ── Circuit builder ────────────────────────────────────────────────────────


def build_ghz_ir(n: int) -> QBCircuit:
    circ = QBCircuit(n_qubits=n, n_clbits=n, name=f"ghz_{n}")
    circ.add_gate(QBGate(name="h", qubits=(0,)))
    for i in range(n - 1):
        circ.add_gate(QBGate(name="cx", qubits=(i, i + 1)))
    for i in range(n):
        circ.add_measurement(i, i)
    return circ


# ── Helpers ────────────────────────────────────────────────────────────────


def centroid(layout: dict[int, int]) -> float:
    phys = list(layout.values())
    return sum(phys) / len(phys) if phys else 0.0


def region_str(layout: dict[int, int]) -> str:
    phys = sorted(layout.values())
    return f"{phys[0]}-{phys[-1]}"


def count_2q_after_routing(
    layout: dict[int, int],
    circuit: QBCircuit,
    qiskit_target: Target,
) -> int:
    """Trial-transpile with given initial layout and count post-routing 2Q gates."""
    from qiskit import QuantumCircuit, transpile

    n = circuit.n_qubits
    qc = QuantumCircuit(n, n)
    qc.h(0)
    for i in range(n - 1):
        qc.cx(i, i + 1)
    qc.measure(range(n), range(n))

    layout_list = [layout[i] for i in range(n)]
    tc = transpile(
        qc,
        target=qiskit_target,
        optimization_level=1,
        initial_layout=layout_list,
        seed_transpiler=42,
    )
    return sum(
        1
        for inst in tc.data
        if len(inst.qubits) == 2
        and inst.operation.name not in ("barrier", "measure", "reset")
    )


def score_layout(mapper: CalibrationMapper, layout: dict[int, int], circuit: QBCircuit) -> float:
    interactions = CalibrationMapper._extract_interactions(circuit)
    return mapper._score_layout(layout, interactions, circuit)


# ── Main ───────────────────────────────────────────────────────────────────


def main() -> None:
    fixture = Path("tests/fixtures/calibration_snapshots/ibm_fez_2026_03_14.json")
    if not fixture.exists():
        console.print(f"[red]Missing fixture: {fixture}[/red]")
        sys.exit(1)

    props = BackendProperties.from_qubitboost_json(fixture)
    console.print(
        f"[bold]Loaded calibration:[/bold] {props.n_qubits} qubits, "
        f"{len(props.gate_properties)} gates"
    )
    console.print(f"Timestamp: {props.timestamp}\n")

    target = build_target(props)

    for n in GHZ_SIZES:
        console.rule(f"[bold cyan]GHZ-{n}[/bold cyan]")
        circ = build_ghz_ir(n)

        mapper = CalibrationMapper(
            props,
            config=CalibrationMapperConfig(
                max_candidates=500,
                vf2_call_limit=50_000,
                top_k=20,
                max_per_region=3,
            ),
            qiskit_target=None,  # don't trigger rescore yet
        )

        interactions = CalibrationMapper._extract_interactions(circ)

        # ── Step 1: raw candidates from _find_top_k_layouts ──────────────
        raw_candidates = mapper._find_top_k_layouts(circ, interactions)

        console.print(
            f"\n[bold yellow]STEP 1 — Raw candidates from _find_top_k_layouts():[/bold yellow] "
            f"{len(raw_candidates)} returned"
        )

        raw_table = Table(
            "Rank", "Physical Qubits", "Centroid", "Region (min-max)", "Cal Score",
            title=f"GHZ-{n}: Raw candidates (pre-diversity)",
            show_lines=False,
        )

        raw_centroids: list[float] = []
        raw_regions: list[str] = []
        for i, layout in enumerate(raw_candidates):
            phys = [layout[q] for q in range(n)]
            c = centroid(layout)
            r = region_str(layout)
            s = score_layout(mapper, layout, circ)
            raw_centroids.append(c)
            raw_regions.append(r)
            raw_table.add_row(
                str(i),
                " ".join(str(q) for q in phys),
                f"{c:.1f}",
                r,
                f"{s:.6f}",
            )

        console.print(raw_table)

        distinct_raw_regions = len(set(raw_regions))
        unique_centroids = len({round(c, 0) for c in raw_centroids})
        console.print(
            f"  Distinct regions (min-max): [bold]{distinct_raw_regions}[/bold]"
        )
        console.print(
            f"  Distinct centroid buckets (rounded): [bold]{unique_centroids}[/bold]"
        )

        # ── Step 2: diversity filter ──────────────────────────────────────
        diverse_candidates = mapper._diversify_candidates(raw_candidates)

        console.print(
            f"\n[bold yellow]STEP 2 — After _diversify_candidates():[/bold yellow] "
            f"{len(raw_candidates)} -> {len(diverse_candidates)} candidates"
        )

        changed = (
            len(raw_candidates) != len(diverse_candidates)
            or any(
                set(raw_candidates[i].values()) != set(diverse_candidates[i].values())
                for i in range(min(len(raw_candidates), len(diverse_candidates)))
            )
        )
        console.print(
            f"  Did diversity filter change anything? "
            f"[{'green' if changed else 'red'}]{'YES' if changed else 'NO — identical set'}[/]"
        )

        div_table = Table(
            "Rank", "Physical Qubits", "Centroid", "Region (min-max)", "Cal Score",
            title=f"GHZ-{n}: Diverse candidates (post-diversity)",
            show_lines=False,
        )

        div_regions: list[str] = []
        for i, layout in enumerate(diverse_candidates):
            phys = [layout[q] for q in range(n)]
            c = centroid(layout)
            r = region_str(layout)
            s = score_layout(mapper, layout, circ)
            div_regions.append(r)
            div_table.add_row(
                str(i),
                " ".join(str(q) for q in phys),
                f"{c:.1f}",
                r,
                f"{s:.6f}",
            )

        console.print(div_table)
        distinct_div_regions = len(set(div_regions))
        console.print(f"  Distinct regions after diversity: [bold]{distinct_div_regions}[/bold]")

        # ── Step 3: post-routing rescore ──────────────────────────────────
        console.print(
            f"\n[bold yellow]STEP 3 — _post_routing_rescore() analysis:[/bold yellow] "
            f"trial-transpiling {len(diverse_candidates)} candidates"
        )

        rescore_table = Table(
            "Rank", "Physical Qubits", "Region", "Cal Score",
            "2Q Gates\n(post-route)", "Selected?",
            title=f"GHZ-{n}: Post-routing rescore (opt_level=1)",
            show_lines=False,
        )

        counts: list[int] = []
        cal_scores_pr: list[float] = []
        failed: list[int] = []

        for i, layout in enumerate(diverse_candidates):
            try:
                two_q = count_2q_after_routing(layout, circ, target)
                counts.append(two_q)
            except Exception as exc:
                console.print(f"  [red]Trial transpile failed for candidate {i}: {exc}[/red]")
                counts.append(-1)
                failed.append(i)
            cal_scores_pr.append(score_layout(mapper, layout, circ))

        # Replicate post_routing_rescore selection logic
        best_idx = 0
        best_2q = float("inf")
        best_cal = float("inf")
        for i, (two_q, cal_s) in enumerate(zip(counts, cal_scores_pr)):
            if two_q < 0:
                continue
            if (two_q, cal_s) < (best_2q, best_cal):
                best_2q = two_q
                best_cal = cal_s
                best_idx = i

        for i, layout in enumerate(diverse_candidates):
            phys = [layout[q] for q in range(n)]
            r = region_str(layout)
            s = cal_scores_pr[i]
            two_q = counts[i]
            selected = i == best_idx
            rescore_table.add_row(
                str(i),
                " ".join(str(q) for q in phys),
                r,
                f"{s:.6f}",
                str(two_q) if two_q >= 0 else "ERR",
                "[bold green]<<< SELECTED[/bold green]" if selected else "",
            )

        console.print(rescore_table)

        unique_2q_counts = set(c for c in counts if c >= 0)
        console.print(
            f"\n  [bold]2Q gate counts seen:[/bold] {sorted(unique_2q_counts)}"
        )
        console.print(
            f"  All identical? "
            f"[{'red' if len(unique_2q_counts) <= 1 else 'green'}]"
            f"{'YES — rescore cannot differentiate candidates!' if len(unique_2q_counts) <= 1 else 'NO — rescore has signal'}"
            f"[/]"
        )

        selected_layout = diverse_candidates[best_idx]
        selected_phys = [selected_layout[q] for q in range(n)]
        console.print(
            f"\n  [bold]Post-routing selected:[/bold] qubits={selected_phys}, "
            f"region={region_str(selected_layout)}, "
            f"2Q gates={best_2q if best_2q != float('inf') else 'N/A'}, "
            f"cal_score={best_cal:.6f}"
        )

        # ── Summary for this GHZ size ─────────────────────────────────────
        console.print(f"\n[bold]SUMMARY GHZ-{n}:[/bold]")
        console.print(
            f"  Raw candidates: {len(raw_candidates)}, "
            f"distinct regions: {distinct_raw_regions}"
        )
        console.print(
            f"  After diversity: {len(diverse_candidates)}, "
            f"distinct regions: {distinct_div_regions}"
        )
        console.print(
            f"  Post-routing 2Q counts: {sorted(unique_2q_counts)} — "
            f"{'SAME (no signal)' if len(unique_2q_counts) <= 1 else 'DIFFERENT (rescore works)'}"
        )
        console.print()

    # ── Overall diagnosis ─────────────────────────────────────────────────
    console.rule("[bold red]DIAGNOSIS[/bold red]")
    console.print(
        "\nCheck the per-GHZ summaries above to answer:\n"
        "  Q1. Are candidates from different regions generated?\n"
        "      -> Look at 'distinct regions' in STEP 1 raw candidates.\n"
        "         If = 1, VF2 is stuck in one region (windowing failed).\n"
        "\n"
        "  Q2. Does diversity filter change anything?\n"
        "      -> 'Did diversity filter change anything?' in STEP 2.\n"
        "         If NO, either only 1 region exists OR candidates already diverse.\n"
        "\n"
        "  Q3. Does post-routing rescore see different 2Q counts?\n"
        "      -> 'All identical?' in STEP 3.\n"
        "         If YES (all same), rescore picks by cal_score tiebreak = same as\n"
        "         pre-routing selection. Post-routing adds no value in that case.\n"
    )


if __name__ == "__main__":
    main()
